name: Selenium ide CI

on:
  push:
      branches:
              - main
jobs:
  build:
    runs-on: ubuntu-lates
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .Net COre
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependecies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run test
        run: dotnet test --verbosity normal
        